export const suggestMePrompts = [
    'a man trying on a suit for a formal event',
    'a woman trying on a summer dress for a beach vacation',
    'a child trying on a superhero costume for Halloween',
    'a man trying on a winter coat for skiing',
    'a woman trying on workout clothes for a fitness class',
    'a child trying on a princess costume for a school play',
    'a man trying on a tuxedo for a wedding',
    'a woman trying on a party dress for a birthday celebration',
    'a child trying on a school uniform for the first day of school',
    'a man trying on a business suit for a job interview',
    'a woman trying on a bridesmaid dress for a wedding',
    'a child trying on a superhero costume for a costume party',
    'a man trying on a casual t-shirt and jeans for a weekend outing',
    'a woman trying on a formal gown for a gala event',
    'a child trying on a Halloween costume of their favorite cartoon character',
    'a man trying on a traditional cultural outfit for a cultural festival',
    'a woman trying on a swimsuit for a beach vacation',
    'a child trying on a sports jersey of their favorite team',
    'a man trying on a hiking outfit for an outdoor adventure',
    'a woman trying on a traditional dress for a cultural ceremony',
    'a child trying on a school uniform for picture day',
    'a man trying on a chef\'s coat for a cooking class',
    'a woman trying on a maternity dress for a baby shower',
    'a child trying on a firefighter costume for a career day at school',
    'a man trying on a cycling outfit for a bike race',
    'a woman trying on a bridesmaid dress for a friend\'s wedding',
    'a child trying on a dinosaur costume for a themed birthday party',
    'a man trying on a formal suit for a black-tie event',
    'a woman trying on a summer dress for a garden party',
    'a child trying on a superhero costume for a comic convention',
    'a man trying on a casual outfit for a day at the park',
    'a woman trying on a cocktail dress for a night out',
    'a child trying on a fairy costume for a school performance',
    'a man trying on a traditional costume for a cultural celebration',
    'a woman trying on a bikini for a tropical vacation',
    'a child trying on a soccer uniform for a sports tournament',
    'a man trying on a ski suit for a winter vacation',
    'a woman trying on a prom dress for a high school dance',
    'a child trying on a pirate costume for a themed party',
    'a man trying on a business suit for a corporate event',
    'a woman trying on a formal gown for a red carpet event',
    'a child trying on a Halloween costume of a scary monster',
    'a man trying on a casual outfit for a casual dinner',
    'a woman trying on a traditional dress for a traditional wedding',
    'a child trying on a superhero costume for a school event',
    'a man trying on a tuxedo for a special occasion',
    'a woman trying on a party dress for a night on the town',
    'a child trying on a princess costume for a costume contest',
    'a man trying on a casual t-shirt and jeans for everyday wear',
    'a woman trying on a formal gown for a charity gala',
    'a child trying on a Halloween costume of their favorite movie character',
    'a man trying on a traditional cultural outfit for a cultural performance',
    'a woman trying on a swimsuit for a pool party',
    'a child trying on a sports jersey of their sports idol',
    'a man trying on a hiking outfit for a nature hike',
    'a woman trying on a traditional dress for a traditional ceremony',
    'a child trying on a school uniform for a school event',
    'a man trying on a chef\'s coat for a cooking competition',
    'a woman trying on a maternity dress for a maternity photoshoot',
    'a child trying on a firefighter costume for a community event',
    'a man trying on a cycling outfit for a cycling race',
    'a woman trying on a bridesmaid dress for a bridal shower',
    'a child trying on a dinosaur costume for a dinosaur-themed party',
    'a man trying on a formal suit for a formal gathering',
    'a woman trying on a summer dress for a summer picnic',
    'a child trying on a superhero costume for a superhero-themed birthday party',
    'a man trying on a casual outfit for a casual outing',
    'a woman trying on a cocktail dress for a cocktail party',
    'a child trying on a fairy costume for a fairy tale play',
    'a man trying on a traditional costume for a traditional festival',
    'a woman trying on a bikini for a beach photoshoot',
    'a child trying on a soccer uniform for a soccer game',
    'a man trying on a ski suit for a ski trip',
    'a woman trying on a prom dress for a prom night',
    'a child trying on a pirate costume for a pirate-themed party',
    'a man trying on a business suit for a business meeting',
    'a woman trying on a formal gown for a formal dinner',
    'a child trying on a Halloween costume of a spooky ghost',
    'a man trying on a casual outfit for a casual gathering',
    'a woman trying on a traditional dress for a traditional dance',
    'a child trying on a superhero costume for a comic book convention',
    'a man trying on a tuxedo for a glamorous event',
    'a woman trying on a party dress for a birthday celebration',
    'a child trying on a princess costume for a princess-themed party'
];
