export const suggestMePrompts = [
    'same model in a tuxedo',
    'same model in a summer dress',
    'same model in a superhero costume',
    'same model in a winter coat',
    'same model in workout clothes',
    'same model in a princess costume',
    'same model in a party dress',
    'same model in a school uniform',
    'same model in a business suit',
    'same model in a bridesmaid dress',
    'same model in a casual t-shirt and jeans',
    'same model in a formal gown',
    'same model in a Halloween costume',
    'same model in a traditional outfit',
    'same model in a beach outfit',
    'same model in a sports jersey',
    'same model in a hiking outfit',
    'same model in a maternity dress',
    'same model in a firefighter costume',
    'same model in a cycling outfit',
    'same model in a dinosaur costume',
    'same model in a summer dress',
    'same model in a cocktail dress',
    'same model in a fairy costume',
    'same model in a soccer uniform',
    'same model in a ski suit',
    'same model in a prom dress',
    'same model in a pirate costume',
];
