export const suggestMePrompts = [
    'same model trying out a tuxedo',
    'same model trying out a summer dress for a beach vacation',
    'same model trying out a superhero costume for Halloween',
    'same model trying out a winter coat for skiing',
    'same model trying out workout clothes for a fitness class',
    'same model trying out a princess costume for a school play',
    'same model trying out a party dress for a birthday celebration',
    'same model trying out a school uniform for the first day of school',
    'same model trying out a business suit for a job interview',
    'same model trying out a bridesmaid dress for a wedding',
    'same model trying out a casual t-shirt and jeans for a weekend outing',
    'same model trying out a formal gown for a gala event',
    'same model trying out a Halloween costume of their favorite cartoon character',
    'same model trying out a traditional cultural outfit for a cultural festival',
    'same model trying out an outfit for a beach vacation',
    'same model trying out a sports jersey of their favorite team',
    'same model trying out a hiking outfit for an outdoor adventure',
    'same model trying out a maternity dress for a baby shower',
    'same model trying out a firefighter costume for a career day at school',
    'same model trying out a cycling outfit for a bike race',
    'same model trying out a dinosaur costume for a themed birthday party',
    'same model trying out a summer dress for a garden party',
    'same model trying out a cocktail dress for a night out',
    'same model trying out a fairy costume for a school performance',
    'same model trying out an outfit for a tropical vacation',
    'same model trying out a soccer uniform for a sports tournament',
    'same model trying out a ski suit for a winter vacation',
    'same model trying out a prom dress for a high school dance',
    'same model trying out a pirate costume for a themed party',
    'same model trying out a traditional dress for a traditional wedding',
];
